version: '2'

volumes:
 db_ov_data:

services:

  db:
    container_name: db-ov
    build: database
    ports:
      - "5432:5432"
    expose:
     - "5432"
    environment:
      DEBUG: "false"
    volumes:
      - db_ov_data:/var/lib/postgresql/data      
networks:
  default:
    external:
      name: ev-ov     