version: '2'

services:

  db:
    container_name: db
    build: database
    ports:
      - "5432:5432"
    expose:
     - "5432"
    environment:
      DEBUG: "false"
networks:
  default:
    external:
      name: ev      