version: '2'

volumes:
    deegree_config_ev_ov:

services:
  deegree:
    container_name: deegree-ov
    restart: always
    build: deegree
    expose:
      - "8080"
    environment:
     VIRTUAL_HOST: "evs.local.nl"
    volumes:
      - deegree_config_ev_ov:/root/.deegree/ev
networks:
  default:
    external:
      name: ev-ov