version: '2'

services:
  nginx:
    container_name: proxy
    restart: always
    build: nginx
    ports:
      - "80:80"
    volumes:
      - nginx_logs:/var/log/nginx
  db:
    container_name: db-ov
    restart: always
    build: database
    environment:
      DEBUG: "false"
    volumes:
      - db_ov_data:/var/lib/postgresql/data    
      
  limesurvey:
    container_name: limesurvey-ov
    restart: always
    expose:
     - "80"
    environment:
      VIRTUAL_HOST: "overijssel.ev-signaleringskaart.nl"
    volumes:
      - upload:/app/upload
    build: 
      context: limesurvey
      args:
        - WMSURL=http://overijssel.ev-signaleringskaart.nl/services/plangebied_wms_ov
        - TOETSSERVLETURL=http://overijssel.ev-signaleringskaart.nl/toets
        
  deegree:
    container_name: deegree-ov
    restart: always
    build: deegree
    depends_on:
      - db
    expose:
      - "8080" 

  backup:
    image: idgis/postgresql-backup
    restart: always
    environment:
      # format: $DB_HOST:$DB_PORT:$DB_NAME:$DB_USER:$DB_PASSWORD
      - DATABASE_0=db-ov:5432:ev_lime_ov:postgres:${DB_PG_PASSWORD}
      - DATABASE_1=db-ov:5432:ev_services_ov:postgres:${DB_PG_PASSWORD}
      - SFTP_USER=${BACKUP_SFTP_USER}
      - SFTP_PASSWORD=${BACKUP_SFTP_PASSWORD}
      - SFTP_HOST=${BACKUP_SFTP_HOST}
      - SFTP_PORT=${BACKUP_SFTP_PORT}
      - BACKUP_NAME=backup/${BACKUP_CLIENT}/db

volumes:
  db_ov_data:
  upload:
  nginx_logs:

networks:
  default:
    external:
      name: ev-ov 
  