version: '2'

services:
  limesurvey:
    container_name: limesurvey-ov
    expose:
     - "80"
    environment:
      LETSENCRYPT_EMAIL: "support@idgis.nl"
      LETSENCRYPT_HOST: "ev-signalering-overijssel.idgis.eu"
      VIRTUAL_HOST: "ev-signalering-overijssel.idgis.eu"
    volumes:
      - upload:/app/upload
    build: 
      context: limesurvey
      args:
        - WMSURL=http://ev-services-ov.idgis.eu/services/plangebied_wms_ov
        - TOETSSERVLETURL=http://ev-services-ov.idgis.eu/veiligheidstoetsservlet/toets

volumes:
  upload:
networks:
  default:
    external:
      name: ev-ov 
  